### ISSUE TITLE
WHOWAS segmentation fault

### ISSUE THREAD

**Issue by divinepet** [levensta/IRC-Server#3]
case: 

1. запускаем сервер, коннект через nc
2. после регистрации меняем никнейм командой NICK на новый
3. используем команду WHOWAS на старый никнейм с любой цифрой в третьем аргументе (WHOWAS oldNickName 2)

Ожидается: информация по неиспользуемому никнейму
Результат: segmentation faut на сервере

Некорректное поведение только при третьем аргументе

**Comment by levensta** [comment]
Исправлено и добавлено в v1.2.2 release.
Коммит: https://github.com/levensta/IRC-Server/commit/abf2e2c4e95236bc056b641d050cfc25de91372d
