### ISSUE TITLE
incorrect WHOWAS command

### ISSUE THREAD

**Issue by divinepet** [levensta/IRC-Server#4]
При просмотре информации по никнейму клиента, который был и отключился, выдается 406 ошибка
По стандарту ожидается актуальная информация по нику, так как клиент был на сервере

**Comment by levensta** [comment]
Исправлено и добавлено в v1.2.2 release.
Коммит: https://github.com/levensta/IRC-Server/commit/abf2e2c4e95236bc056b641d050cfc25de91372d
