### ISSUE TITLE
PING command incorrect

### ISSUE THREAD

**Issue by divinepet** [levensta/IRC-Server#6]
case: Подключить два клиента к серверу.  (если кейс не всплывает, изменить настройки таймаута с 60 и 120 на 10 и 20 и при необходимости обратно, также попробовать использовать REHASH)
Ожидание: Одинаковая работа команды ping для обоих клиентов
Результат: оба клиента получают неоднократно команду ping от сервера, таймаут на ответ работает некорректно, клиента не кикает с сервера
настройки 60/120:
<img width="1180" alt="Снимок экрана 2021-11-16 в 19 37 36" src="https://user-images.githubusercontent.com/59801674/142005852-49c1afdf-c8aa-41e9-a175-363254cf3224.png">

**Comment by levensta** [comment]
Не удалось повторить кейс
